//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.RentPayments = new HashSet<RentPayment>();
        }
    
        public int FlatId { get; set; }
        public int TenantId { get; set; }
        public int AgencyId { get; set; }
        public System.DateTime RentPaymentDay { get; set; }
        public System.DateTime EndDate { get; set; }
        public int StartDate { get; set; }
        public decimal RentAmount { get; set; }
        public int Id { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentPayment> RentPayments { get; set; }
    }
}
