//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentPayment
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
